# Generated by Django 4.2.16 on 2024-09-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_book_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.99, max_digits=10, null=True),
        ),
    ]
